version: '3.8'

services:
  flaskgif:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskgif
    ports:
      - "5000:5000"
    env_file: 
      - .env
    depends_on:
      - gif-db
    networks:
      - flaskapp-network

  gif-db:
    image: mysql:5.7
    container_name: gif-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    networks:
      - flaskapp-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: flaskapp-test
    depends_on:
      - flaskgif
    networks:
      - flaskapp-network

networks:
  flaskapp-network:
    driver: bridge

volumes:
  mysql-data:


# version: '3.8'
# #to do: add .env file for securty and add it to .gitignore
# #init intilize database from docker compose
# services:
#   flaskgif:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: flaskgif
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_ENV=development
#       - DATABASE_HOST=gif-db
#       - DATABASE_PORT=3306
#       - DATABASE_NAME=flaskdb
#       - DATABASE_USER=yuvalbenar
#       - DATABASE_PASSWORD=password
#     depends_on:
#       - gif-db
#     networks:
#       - flaskapp-network

#   gif-db:
#     image: mysql:5.7
#     container_name: gif-db
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: flaskdb
#       MYSQL_USER: yuvalbenar
#       MYSQL_PASSWORD: password
#     ports:
#       - "3307:3306"
#     networks:
#       - flaskapp-network
#     volumes:
#       - mysql-data:/var/lib/mysql

# networks:
#   flaskapp-network:
#     driver: bridge

# volumes:
#   mysql-data:
