name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Trigger on push to the develop branch
  pull_request:
    branches:
      - develop  # Trigger on pull request to the develop branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Build and start containers in the background
      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yaml up --build -d

      # Run unit tests (adjust this step based on your testing setup)
      - name: Run tests
        run: |
          docker-compose -f docker-compose.yaml run test

      # Shut down containers after tests
      - name: Clean up containers
        run: |
          docker-compose -f docker-compose.yaml down --volumes --remove-orphans

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This should be 'build' instead of 'test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/CLI-action@v1

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        run: |
          az webapp up --name flasksqlgif-base --resource-group yuvirg --plan ASP-yuvirg-bbdc --location "Canada Central" --sku B1
