name: CI/CD Pipeline for Flask SQL GIF App

on:
  push:
    branches:
      - develop  # Trigger the workflow on push to the develop branch
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Build Docker image
        run: |
          docker build -t yuvalbenar/flasksqlgifbase:v1.0.82 .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push Docker image to Docker Hub
        run: |
          docker push yuvalbenar/flasksqlgifbase:v1.0.82

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run tests using curl
        run: |
          curl --fail http://localhost:5000 || exit 1

      - name: Bandit security check
        run: |
          pip install bandit
          bandit -r app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli-action@v1
        with:
          azcliversion: 2.28.0

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App for Containers
        run: |
          az webapp config container set --name flasksqlgif-base --resource-group yuvirg --docker-custom-image-name yuvalbenar/flasksqlgifbase:v1.0.82
