name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Change this to your preferred branch if necessary
  pull_request:
    branches:
      - develop  # Same here

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yaml up --build -d

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests in the test container
        run: |
          docker-compose -f docker-compose.yaml run --rm test

      - name: Shut down containers
        run: |
          docker-compose -f docker-compose.yaml down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli-action@v1

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        run: |
          az webapp up --name flasksqlgif-base --resource-group yuvirg --plan ASP-yuvirg-bbdc --location "Canada Central" --sku B1
